FROM postgres:18.1
LABEL ALIAS=postgresql

FROM quay.io/keycloak/keycloak:26.4.7
LABEL ALIAS=keycloak

FROM mysql:9.5.0

FROM mongo:8.2.3
LABEL ALIAS=mongodb

FROM memcached:1.6.40-alpine

FROM redis:8.4.0

FROM apache/kafka-native:4.1.1
LABEL ALIAS=kafka

FROM apachepulsar/pulsar:4.1.2
LABEL ALIAS=pulsar

LABEL ALIAS=consul

FROM prom/prometheus:v3.8.1
LABEL ALIAS=prometheus

FROM prom/alertmanager:v0.30.0
LABEL ALIAS=prometheus-alertmanager

FROM grafana/grafana:12.3.1
LABEL ALIAS=grafana

FROM eclipse-temurin:17-jre-focal
LABEL ALIAS=java-jre

FROM openzipkin/zipkin:3.5.1
LABEL ALIAS=zipkin